FROM node:16-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock* ./
RUN yarn --frozen-lockfile && yarn cache clean

COPY . .

RUN yarn build

ENV NODE_ENV production

CMD ["./entrypoint.sh"]
