version: '3.5'

services:
  app:
    container_name: chat-app
    image: chat-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nest-network

  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_MAIN: ${POSTGRES_DB_MAIN}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST}

    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/entrypoint:/docker-entrypoint-initdb.d
    networks:
      - nest-network

networks:
  nest-network:
